blogproject/blog/urls.py
# -*- coding:utf-8 -*-


from django.conf.urls import url

from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.details, name='details'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]

blogproject/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'', include('comments.urls'))
    # url(r'^index$', include('blog.urls'))
]

blogproject/comments/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.



class Category(models.Model):
    """
    django 要求我们必须继承 models.Model 类，
    Category 只需要一个简单的分类名 name 就可以了。

    CharField 指定了 name 的数据类型，
    CharField 是字符型，
    max_length 指定其最大长度，
    超过这个长度的分类名就不能被存入数据库。

    当然 django 还为我们提供了各种各样的类型，
    如日期时间类型 DateTimeField、
    整数类型 IntegerField 等等。
    django 内置的类型全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        # python_2_unicode_compatible 装饰器用于兼容 Python2
        return self.name

class Tag(models.Model):
    """
    标签 Tag 也比较简单，
    和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        # python_2_unicode_compatible 装饰器用于兼容 Python2
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。
    # 比较短的字符串存储可以使用 CharField，
    # 但对于文章的正文来说可能会是一大段文本，
    # 因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分表表示了文章的创建时间和最后一次修改时间，
    # 存储时间的列用 DateTimeField。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，
    # 但默认情况下 CharField 要求我们必须存入数据，
    # 否则就会报错。
    # 指定 blank=True 后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)

    # 这是分类与标签，
    # 分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类与标签对应的表关联起来，
    # 但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，
    # 但是一个分类下可以有很多篇文章，
    # 所以我们使用的是 ForeignKey，
    # 即一对多的关系。
    # 而对于标签来说，
    # 一篇文章可以有多个标签，
    # 同一个标签下也可能有多篇文章，
    # 所以我们使用 ManyToManyField，
    # 表明这是多对多的关系。
    # 同时我们规定文章可以没有标签，
    # 因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，
    # 请看教程中的解释，
    # 亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者
    # 这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，
    # 专门用于处理网站用户的注册、登录等流程，
    # User 是 django 为我们已经写好的用户模型，
    # 这里我们通过 ForeignKey 把文章和 User 关联起来，
    # 因为我们规定一篇文章只能有一个作者，
    # 而一个作者可能会写多篇文章，
    # 因此这是一对多的关系，
    # 和 Category 类似。
    author = models.ForeignKey(User)

    def __str__(self):
        # python_2_unicode_compatible 装饰器用于兼容 Python2
        return self.title

    def get_absolute_url(self):
        return reverse('blog:details', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']


    ''' 
from blog.models import Category, Tag, Post
from django.utils import timezone
from django.contrib.auth.models import User

user = User.objects.get(username='admin')
c = Category.objects.get(name='category test')

p = Post(title='title test', body='body test', created_time=timezone.now(), modified_time=timezone.now(), category=c, author=user)
p.save()'''

blogproject/comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]


    '''这里我们会记录评论用户的 name（名字）、email（邮箱）、url（个人网站），
    用户发表的内容将存放在 text 字段里，created_time 记录评论时间。最后，这
    个评论是关联到某篇文章（Post）的，由于一个评论只能属于一篇文章，一篇文章
    可以有多个评论，是一对多的关系，因此这里我们使用了 ForeignKey。关于 ForeKey
    的只是我们前面已有介绍。'''

blogproject/comments/forms.py
# -*- coding:utf-8 -*-

from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email','text']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': "名字",
            }),
            'email': forms.TextInput(attrs={
                'placeholder': "邮箱",
            }),

        }

blogproject/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse

from comments.forms import CommentForm
from .models import Post,Category
import markdown



def index(request):
    post_list=Post.objects.all().order_by('-created_time')
    return render(request,'blog/index.html',{'post_list':post_list})




def details(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.body = markdown.markdown(
        post.body,
        extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ]
    )
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {'post': post,
               'form': form,
               'comment_list': comment_list
               }
    return render(request, 'blog/detail.html', context=context)


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})

blogproject/comments/views.py
from django.shortcuts import render,redirect,get_object_or_404

# Create your views here.
from blog.models import Post
from .models import Comment
from .forms import CommentForm


def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来
    # 这里我们使用了 django 提供的一个快捷函数 get_object_or_404
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户
    post = get_object_or_404(Post, pk=post_pk)

    # http 请求有 get 和 post 两种方法，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据
    if request.method == 'POST':
        # 用户提交的数据存在 request.POST
        # 我们利用这些数据构造了 CommentForm 的实例，这样 django 的表单就生成了
        form = CommentForm(request.POST)

        # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例
            # 但还不保存数据到数据库
            comment = form.save(commit=False)
            # 将评论和被评论的文章关联起来
            comment.post = post
            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()

            # 重定向到 post 的详情页
            return redirect(post)

        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误
            # 因此我们传了三个模板变量给 detail.html
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            # 注意这里我们用到了 post.comment_set.all() 方法
            # 这个用法有点类似于 Post.objects.all()
            # 其作用是获取这篇 post 下的的全部评论
            # 因为 Post 和 Comment 是 ForeignKey 关联的
            # 因此使用 post.comment_set.all() 反向查询全部评论
            # 正向查询就直接是 comment.post
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页
    return redirect(post)

blogproject/templates/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>
		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
{#        <link rel="stylesheet" href="{% static 'blog/css/friendly.css' %}">#}
	    <!-- js -->
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
{#							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>#}
						    <h1><a href="{% url 'blog:index' %}"><b>博客主页</b></a></h1>
                        </div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
		<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
                         {% block main %}
                        {% endblock main %}
					</main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">
							<h3 class="widget-title">最新文章</h3>
                            {% get_recent_posts as recent_post_list %}
                                                    <ul>
                                {% for post in recent_post_list %}
                                <li>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
						</div>
						<div class="widget widget-archives">
							<h3 class="widget-title">归档</h3>
							{% archives as date_list %}
                              <ul>
                                {% for date in date_list %}
                                <li>
                                  <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                                </li>
                                {% endfor %}
                              </ul>
						</div>

						<div class="widget widget-category">
							<h3 class="widget-title">分类</h3>
							 {% get_categories as category_list %}
                              <ul>
                                {% for category in category_list %}
                                <li>
                                  <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                                {% endfor %}
                              </ul>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com -More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{% url 'blog:index' %}">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js'%}"></script>

	</body>
</html>

blogproject/templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blogproject/templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
                        {% block main %}
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">{{ post.title }}</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">{{ post.category.name }}</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
			
									<span class="post-author"><a href="#">{{ post.author }}</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>{{ post.body|safe }}</p>
							</div>
						</article>

                        <section class="comment-area">
							<h2>留下你的评论</h2>
                            <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                                      {% csrf_token %}
                                      <div class="row">
                                        <div class="col-md-4">
                                          <label for="{{ form.name.id_for_label }}">Name:</label>
                                          {{ form.name }}
                                          {{ form.name.errors }}
                                        </div>
                                        <div class="col-md-4">
                                          <label for="{{ form.email.id_for_label }}">Email:</label>
                                          {{ form.email }}
                                          {{ form.name.errors }}
                                        </div>
{#                                        <div class="col-md-4">#}
{#                                          <label for="{{ form.url.id_for_label }}">Url:</label>#}
{#                                          {{ form.url }}#}
{#                                          {{ form.url.errors }}#}
{#                                        </div>#}
                                        <div class="col-md-12">
                                          <label for="{{ form.text.id_for_label }}">Comment:</label>
                                          {{ form.text }}
                                          {{ form.text.errors }}
                                          <button type="submit"><span>发表</span></button>
                                        </div>
                                      </div>    <!-- row -->
                                    </form>
                            <div class="comment-list">
                              <h2>评论列表</h2>
                              <ul class="list-unstyled">
                                {% for comment in comment_list %}
                                <li class="comment-item">
                                  <span class="name">{{ comment.name }}</span>
                                  <time class="date">{{ comment.created_time }}</time>
                                  <div class="text">
                                    {{ comment.text }}
                                  </div>
                                </li>
                                {% empty %}
                                暂无评论
                                {% endfor %}
                              </ul>
                            </div>
                        </section>
                        {% endblock %}

blogproject/templates/blog/index.html
{% extends 'base.html' %}
					{% block main %}
                        {% for post in post_list %}
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
{#									<a href="">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>#}
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </h1>
								<div class="entry-meta">
                                        <span class="post-category">
                                          <a href="#">{{ post.category.name }} </a>
                                        </span>

                                        <span class="post-date">
                                          <a href="#">
                                            <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}         </time>
                                          </a>
                                        </span>

                                        <span class="post-author"><a href="#">{{ post.author }} </a></span>

                                        <span class="comments-link"><a href="#">4 Comments</a></span>

								</div>
							</header>
							<div class="entry-content clearfix">
								<p>{{ post.excerpt }}</p>
								<div class="read-more cl-effect-14">
									<a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
                        {% empty %}
                        <div class="no-post">暂时还没有发布的文章！</div>
                        {% endfor %}
                    {% endblock %}